[package]
name = "asteroids"
version = "0.1.0"
authors = ["Ilya Bogdanov <fumlead@gmail.com>"]

[dependencies]
rand = "0.4"
three = { git = "https://github.com/three-rs/three/" }
euler = { git = "https://github.com/alteous/euler/", features = ["mint"] }
